# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-21 14:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('created_time', models.DateTimeField(db_column=b'create_time', default=django.utils.timezone.now)),
                ('update_time', models.DateTimeField(db_column=b'update_time', null=True)),
                ('record_status', models.CharField(default=b'LIVE', max_length=200)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('eventname', models.CharField(max_length=255)),
                ('locname', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('evenstart', models.DateTimeField(default=django.utils.timezone.now)),
                ('evenend', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'api_event',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('created_time', models.DateTimeField(db_column=b'create_time', default=django.utils.timezone.now)),
                ('update_time', models.DateTimeField(db_column=b'update_time', null=True)),
                ('record_status', models.CharField(default=b'LIVE', max_length=200)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('schedulename', models.CharField(max_length=255)),
                ('schedulestart', models.DateTimeField(default=django.utils.timezone.now)),
                ('scheduleend', models.DateTimeField(default=django.utils.timezone.now)),
                ('event', models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, related_name='schedule_event', to='api.Event')),
            ],
            options={
                'db_table': 'api_schedule',
            },
        ),
    ]
