# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-21 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('created_time', models.DateTimeField(db_column=b'create_time', default=django.utils.timezone.now)),
                ('update_time', models.DateTimeField(db_column=b'update_time', null=True)),
                ('record_status', models.CharField(default=b'LIVE', max_length=200)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=100)),
                ('qty', models.IntegerField(default=100)),
            ],
            options={
                'db_table': 'api_ticket',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('created_time', models.DateTimeField(db_column=b'create_time', default=django.utils.timezone.now)),
                ('update_time', models.DateTimeField(db_column=b'update_time', null=True)),
                ('record_status', models.CharField(default=b'LIVE', max_length=200)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('custname', models.CharField(max_length=255)),
                ('datetrx', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'api_transaction',
            },
        ),
        migrations.AlterField(
            model_name='event',
            name='evenend',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='evenstart',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='scheduleend',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedulestart',
            field=models.DateTimeField(),
        ),
        migrations.AddField(
            model_name='transaction',
            name='event',
            field=models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, related_name='trx_event', to='api.Event'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='event',
            field=models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, related_name='ticket_event', to='api.Event'),
        ),
    ]
