# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-22 00:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180721_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='location',
            fields=[
                ('created_time', models.DateTimeField(db_column=b'create_time', default=django.utils.timezone.now)),
                ('update_time', models.DateTimeField(db_column=b'update_time', null=True)),
                ('record_status', models.CharField(default=b'LIVE', max_length=200)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('locname', models.CharField(max_length=255)),
                ('locmap', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'api_location',
            },
        ),
        migrations.RemoveField(
            model_name='event',
            name='address',
        ),
        migrations.RemoveField(
            model_name='event',
            name='city',
        ),
        migrations.RemoveField(
            model_name='event',
            name='locname',
        ),
        migrations.AddField(
            model_name='location',
            name='event',
            field=models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, related_name='location_event', to='api.Event'),
        ),
    ]
