# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-22 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180722_0051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='event',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='event',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='event',
        ),
        migrations.AddField(
            model_name='schedule',
            name='event_id',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='ticket',
            name='event_id',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='event_id',
            field=models.IntegerField(default=100),
        ),
    ]
