# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-22 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180722_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='evenend',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='evenstart',
            field=models.CharField(max_length=255),
        ),
    ]
